---
- name: Install dependencies
  yum:
    name:
      - git
      - python-pip
    state: present

- name: Cloning ceph-dash from github
  git: repo=https://github.com/Crapworks/ceph-dash.git dest=/etc/ceph/ceph-dash accept_hostkey=yes force=yes

- name: Upgrading jinja2 for ceph-dash
  command: pip install --upgrade jinja2

- name: Update ceph-dash.py
  template: src=ceph-dash.py dest=/etc/ceph/ceph-dash/ceph-dash.py

- name: Executing ceph-dash
  command: python /etc/ceph/ceph-dash/ceph-dash.py
  async: 360000
  poll: 0
